CREATE TABLE `copier_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`multiplier` decimal(10,4) NOT NULL DEFAULT '1.0000',
	`copyStopLoss` boolean NOT NULL DEFAULT true,
	`copyTakeProfit` boolean NOT NULL DEFAULT true,
	`skipPendingOrders` boolean NOT NULL DEFAULT true,
	`scaleTypeId` int NOT NULL DEFAULT 3,
	`scaleTypeName` varchar(50) NOT NULL DEFAULT 'Fixed lot size',
	`active` boolean NOT NULL DEFAULT false,
	`monitorOnly` boolean NOT NULL DEFAULT false,
	`maxSlippage` int NOT NULL DEFAULT 0,
	`forceMinTrade` boolean NOT NULL DEFAULT true,
	`fixMasterBalanceAndEquity` decimal(15,2) NOT NULL DEFAULT '0.00',
	`fixSlaveBalanceAndEquity` decimal(15,2) NOT NULL DEFAULT '0.00',
	`fixedLotSize` decimal(10,2) NOT NULL DEFAULT '0.01',
	`martingaleStrategy` boolean NOT NULL DEFAULT false,
	`openRetry` boolean NOT NULL DEFAULT true,
	`openRetryTimeoutInMinutes` int NOT NULL DEFAULT 10,
	`reverse` boolean NOT NULL DEFAULT false,
	`copyOpenPositions` boolean NOT NULL DEFAULT false,
	`maxOpenPositions` int NOT NULL DEFAULT 0,
	`maxLotSize` decimal(10,2) NOT NULL DEFAULT '0.00',
	`maximumLot` decimal(10,2) NOT NULL DEFAULT '0.00',
	`hideComment` boolean NOT NULL DEFAULT false,
	`forcePositionLotSize` boolean NOT NULL DEFAULT false,
	`ignoreContractSize` boolean NOT NULL DEFAULT false,
	`ignoreCurrency` boolean NOT NULL DEFAULT false,
	`copyMagicNumber` boolean NOT NULL DEFAULT true,
	`copyOriginalComment` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `copier_templates_id` PRIMARY KEY(`id`)
);
